### ISSUE TITLE
Liam

### ISSUE THREAD

**Issue by Olivem1234567** [Olivem1234567/Olivem1234567.github.io#2]
use issues as chat and also ideas

**Comment by LiamM-MTCBs** [comment]
alr sick

**Comment by Olivem1234567** [comment]
videos work but lets leave them out for now

**Comment by LiamM-MTCBs** [comment]
yeah, i was removing them but you got to it before me.

**Comment by Olivem1234567** [comment]
lol

**Comment by Olivem1234567** [comment]
ima figure out how to center text

**Comment by Olivem1234567** [comment]
It worked W

**Comment by LiamM-MTCBs** [comment]
Use the discussions tab now.
